### ISSUE TITLE
Set navigation_with_keys=False explicitly

### ISSUE THREAD

**Issue by scottyhq** [xarray-contrib/xarray-tutorial#244]
Currently this warning is raised: 

> The default value for `navigation_with_keys` will change to `False` in the next release. If you wish to preserve the old behavior for your site, set `navigation_with_keys=True` in the `html_theme_options` dict in your `conf.py` file. Be aware that `navigation_with_keys = True` has negative accessibility implications: https://github.com/pydata/pydata-sphinx-theme/issues/1492

Can pre-empt this change by changing the config:
https://github.com/xarray-contrib/xarray-tutorial/blob/main/_config.yml#L62
```yaml
sphinx:
  config:
    html_theme_options:
      navigation_with_keys: false
```
