### ISSUE TITLE
Add  preview build functionality for PRs

### ISSUE THREAD

**Issue by dcherian** [xarray-contrib/xarray-tutorial#68]

**Comment by scottyhq** [comment]
We've been using Netlify for this on other projects https://jupyterbook.org/publish/netlify.html, and it is very nice to have

It's free, but requires an email account to setup and charges a subscription for multiple team members. So we have a uwhackweek@gmail.com account that several people have access to. I could add the site under that same account for now or does xarray already have an email account like that for other services?

Netlify requires a bit of manual setup to connect the github app (probably similar to reviewNB), but then the action for PRs is pretty straightforward
https://github.com/uwhackweek/jupyterbook-template/blob/main/.github/workflows/netlifypreview.yaml
```
    - name: Deploy Website Preview
      uses: nwtgck/actions-netlify@v1.1
      with:
        publish-dir: './book/_build/html'
        production-deploy: false
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
        enable-commit-comment: false
        enable-pull-request-comment: true
        overwrites-pull-request-comment: true
        alias: deploy-preview-${{ github.event.number }}
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      timeout-minutes: 1
```
